const STORAGE_PREFIX = 'CEC';
const NOTIFICATION_TITLE = 'Chrome Extension Crawler';

const STORAGE_POSTS = `${STORAGE_PREFIX}_posts`;
const STORAGE_KEYWORDS = `${STORAGE_PREFIX}_keywords`;

export {
  STORAGE_POSTS,
  STORAGE_KEYWORDS,
  NOTIFICATION_TITLE
};
